### PR TITLE
adding django tests to github actions

### LINKED ISSUE #96: Include django tests in github actions
Sources I found:
- [https://blog.healthchecks.io/2020/11/using-github-actions-to-run-django-tests/](https://blog.healthchecks.io/2020/11/using-github-actions-to-run-django-tests/)
- [https://www.reddit.com/r/django/comments/13z0u5a/how_should_i_setup_github_actions_django_tests_ci/](https://www.reddit.com/r/django/comments/13z0u5a/how_should_i_setup_github_actions_django_tests_ci/)
- [https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers](https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers)

### PR DESCRIPTION
**Pull request by sh1negg**
Hey there,

in this PR I added [`django.yml`](https://github.com/brendel-group/mission_db/blob/8376c9285ec7646e08dd9a275c979d8d337a8e0d/.github/workflows/django.yml) in our `workflows` folder. With this addition, we added our django tests, which we usually run with`python manage.py test restapi` to our GitHub Actions. This way, the tests automatically run with every push and PR, just like we did with our `ruff` checks.

This resolves #96

### CODE REVIEW

**Comment by pascal260303** [comment]
why not run all tests with `python manage.py test` ?

**Review by DerSimi — CHANGES_REQUESTED** [review]
I agree with Pascal, you only run the restapis. We have already more ig.

**Comment by sh1negg** [comment]
I had to specify which tests I want to run, as it doesn't find any tests, if I'm doing it otherwise 
image.
I will add `python manage.py tests_cli` though.

**Comment by pascal260303** [comment]
I noticed now no tests are run at all, because `manage.py` is in the folder `backend/` but is run at the project root. You can really run all with `python manage.py test backend`

**Review by DerSimi — APPROVED** [review]

**Pull request merged**
