### PR TITLE
Restapi Api Key Authorization

### LINKED ISSUE #136: Protect Rest API with API key

### PR DESCRIPTION
**Pull request by pascal260303**
This PR adds authorization for the REST API.\
I used [this](https://florimondmanca.github.io/djangorestframework-api-key/) module for this.\
Now every request to the REST API has to have an Authorization header in the format
```
Authorization: Api-Key <API_KEY>
```
This can be disabled by setting `DEBUG=True` in the `backend/backend/.env` file.\
Unfortunately the browsable API won't work with this.

API KEYs can be added or removed via the CLI.

The key itself is not stored in the database, just the hash value.

I made changes and added the documentation for the [CLI](https://github.com/brendel-group/mission_db/blob/feature/restapi-api-key/docs/cli/README.md), the [frontend](https://github.com/brendel-group/mission_db/blob/feature/restapi-api-key/docs/frontend/README.md) and the [restapi](https://github.com/brendel-group/mission_db/blob/feature/restapi-api-key/docs/restapi/README.md).

I changed the frontend to use an API KEY if it is set in a new `.env` file in the `frontend/` folder like this:
```bash
VITE_BACKEND_API_KEY = '<API_KEY>'
```

This resolves #136 

## How to test:
To not use any API KEYs start the backend with `DEBUG=True` and confirm that everything works like before.

To use API KEYs set `DEBUG=False` in the `.env` file for the backend, add an API KEY with the CLI, add it to the `.env` file for the frontend and test the frontend.

To manually test the REST API you can use curl like this:
```bash
curl -H "Authorization: Api-Key <API_KEY>" localhost:8000/restapi/missions/
```
to make other requests than GET you can use for example the option `-X DELETE` to make a DELETE request.

### CODE REVIEW

**Comment by pascal260303** [comment]
to fix the test of the frontend run with `npm test`. I had to mock the call of `import.meta.env` which is used to access environmental variables (and variables in `.env`). \
To do this I installed the packet `ts-jest-mock-import-meta` and added configuration in jest.config.cjs.

**Review by DerSimi — COMMENTED** [review]
Hi Pascal, did you overlook something or is this an issue on my side?
image

I installed the new dependencies from requirements.txt

Receive an exception when looking for `api-key` commands.

**Comment by pascal260303** [comment]
Was an error by me, fixed it.

**Comment by pascal260303** [comment]
You also need to run 
```bash
python manage.py migrate
```

**Review by sh1negg — APPROVED** [review]
Hey Pascal,

after your fix, the creation and deletion of api keys over the CLI is now working 👍 Working with `DEBUG=True` lets us work as before and setting it to `False` makes the authentication mandatory, so it works as intended:
image
After creating and inserting the api key, I tried creating and deleting a mission over the CLI, which worked perfectly fine and was also displayed on the frontend after a reload. 
Deleting the api key over the CLI also broke the frontend functionality, so it does it's job:
image
The PR LGTM and can be merged 👍

**Pull request merged**
