### PR TITLE
New handling of null cases in the detail view and in overview

### PR DESCRIPTION
**Pull request by DerSimi**
Hi,
this pr addresses issue #139

I implemented a new handling for null cases in remarks and location, the problem was the following:
And null appears in detail view:
image
This is addressed by new checks and changes to the headline in detail view:
image

### CODE REVIEW

**Comment by SamuABC** [comment]
Without looking at the code, I think that it is not necessary to write "None" in the overview table.
The User knows there is no data when the spot is empty and it is prettier when the table is not full of "None" keywords in the overview. 
What do you think about that?

**Comment by DerSimi** [comment]
I agree. But would leave the improved headline in DetailView.

**Comment by DerSimi** [comment]
Removed the "None" message within Mission Table again, but
`<Table.Td>{row.location === null ? "" : row.location}</Table.Td>`
stays. This was handled by the transform function within the fetch api before, but it will be removed in the future.

image

**Review by SamuABC — APPROVED** [review]
Thanks for removing "None" from the Overview. In the Detail View it makes sense. Overall good handling of the None cases

**Pull request merged**
