### PR TITLE
CLI interactive mode improvements

### PR DESCRIPTION
**Pull request by pascal260303**
I made some improvements for the interactive mode and the CLI in general:
1. When the output is a table it uses Unicode characters for the lines in the table. This behavior is now optional and can be disabled with the environment variable `USE_UNICODE` that can be set to `False` in the .env file. It then uses ASCII characters.
2. The table now correctly displays strings that contain newlines (`\n`). It now prints the second or more lines of such a string in a new line that contains only empty fields or the respective content.
3. The interactive mode now supports multi line input when using quotes. Previously it was only possible to have multi line strings when using arguments and not the interactive mode.
4. When an exception is thrown when using the interactive mode it is printed like normal and the interactive mode is terminated correctly (writing the history to file and potentially more)

I added documentation for the environment variable `USE_UNICODE` and the multi line input.\
And I added a test for the output of multi line strings in the table.

I added the option to disable the usage of Unicode characters, because when using the pager added in #151 on windows with setting `PAGER=less` it doesn't support Unicode characters and prints something unreadable.

## How to test
Use the CLI with the interactive mode and try adding a mission that contains more than one line in the name or notes field.\
Then test the output using `mission list`.
Set `USE_UNICODE=False` in the backend/backend/.env file and test the output again.

### CODE REVIEW

**Comment by pascal260303** [comment]
The environmental variable `USE_UNICODE` is now handled by `environ` which means setting the variables in .env is no longer case sensitive.

**Review by KageKrito — CHANGES_REQUESTED** [review]
The new look of the table with unicode symbols is much better, because the lines are connected. 
Defining USE_UNICODE as True or False in the backend .env correctly switches the look of the table.
With USE_UNICODE=False :
Screenshot from 2024-12-30 12-52-16
With USE_UNICODE=True :
Screenshot from 2024-12-30 12-52-04

However, it seems like there is an error with the linebreak (\n). I tried by adding a mission with the name Test\n2ndLine , here with ID 7, and a mission with the name "Test\n2ndLine" (The same name but with " "), here with ID 8, but both trys of getting a linebreak failed:
Screenshot from 2024-12-30 12-51-52
I'm not sure if I these are just both not the intended way of getting a linebreak or if this is an error. 
Please correct me if I did it the wrong way :)

**Comment by KageKrito** [comment]
I tried the linebreak another way that is mentioned in the documentation by starting the name as a quote and then just pressing 'enter' for the linebreak, here with ID 9,  and this works just as intended:
Screenshot from 2024-12-30 13-09-09

**Comment by pascal260303** [comment]
Typing in `\n` is not the intended way of adding linebreaks and you found the intended way.

**Pull request merged**
