### PR TITLE
Deploy backend to fly-io

### PR DESCRIPTION
**Pull request by mkiefel**

### CODE REVIEW

**Comment by mkiefel** [comment]
> > ead that when you set `DEBUG` to `False` you have to setup an actual webserver to serve the static files so the browsable API still
> 
> Ah OK :) Yep, I can fix that as well. I was just trying to use the JSON API part and not necessarily the UI parts (I hope I got you there). Will fix that in the next days.

Fixed now: https://polybot-mission-db-backend.fly.dev/restapi/missions/create/

**Review by pascal260303 — CHANGES_REQUESTED** [review]
The browsable API now works. Thank you.

But I found another issue:
When trying to delete a mission I get a `Server Error (500)` response.\
This happens when I try to make a `DELETE` request using the browsable API and with `curl`.\
This only happens with missions. A Tag can be deleted using a `DELETE` request.\
When I test it locally, it also works.

**Comment by mkiefel** [comment]
> The browsable API now works. Thank you.
> 
> But I found another issue: When trying to delete a mission I get a `Server Error (500)` response. This happens when I try to make a `DELETE` request using the browsable API and with `curl`. This only happens with missions. A Tag can be deleted using a `DELETE` request. When I test it locally, it also works.

I suspect that's more an issue of the API implementation than the deployment.

Can you please share the `curl` command that you used?

**Comment by mkiefel** [comment]
> The browsable API now works. Thank you.
> 
> But I found another issue: When trying to delete a mission I get a `Server Error (500)` response. This happens when I try to make a `DELETE` request using the browsable API and with `curl`. This only happens with missions. A Tag can be deleted using a `DELETE` request. When I test it locally, it also works.



> The curl command I used:
> 
> ```shell
> curl -X DELETE https://polybot-mission-db-backend.fly.dev/restapi/missions/2
> ```
> 
> I don't know if it's an issue of the deployment or the implementation, because I can't test it locally.

For me this does not even to work locally. I'll try to debug it.

**Comment by pascal260303** [comment]
Now everything works. Thank you.

**Review by pascal260303 — APPROVED** [review]

**Pull request merged**
