### PR TITLE
UI searchable tags

### LINKED ISSUE #46: UI searchable Tags
# Goal
- make a search feature for the tags
- it should be possible to search for multiple tags at once. e.g. tag1 && tag2

### PR DESCRIPTION
**Pull request by SamuABC**
resolves #46

# Changes
- I changed the sortData and the filterData function to also handle the tagSearch. 
- I changed the way tags get displayed and what happens when you click on them
- When clicking a Tag, only the rows with this tag get displayed and the clicked tag gets marked. when clicking more tags, the rows get filtered for all rows which contain all the clicked tags. This implements the "and" search functionality for tags.
grafik
grafik
grafik
For this to work. I had to change the way the tag Picker gets opened in the overview. It now gets opened by the little pencil Button next to the tags

# little fixes
- I removed the redundant tagId from the tag interface

### CODE REVIEW

**Comment by DerSimi** [comment]
You can fix that by rebase this branch to main and complete it using force push.

**Comment by DerSimi** [comment]
> Github thinks the changes on this branch are bigger than they are. This is because I merged two branches (which are now merged in main) into this one during development and now github thinks I did that too.
You can fix that by rebase this branch to main and force push afterwards.

**Comment by SamuABC** [comment]
> > Github thinks the changes on this branch are bigger than they are. This is because I merged two branches (which are now merged in main) into this one during development and now github thinks I did that too.
> 
> 
> 
> You can fix that by rebasing this branch to main and force push afterwards.

Good to know. Thanks for the advice. I'll try it out later

**Review by DerSimi — APPROVED** [review]
Good idea to remove the tagId. In the future, also "tags" in MissionData can be deleted.
Your code is a nice UX addition, good job.

**Pull request merged**
